# Generated by Django 4.1.1 on 2023-05-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
    ]

migrations.RunSQL('UPDATE main_app_user SET last_login = NOW() WHERE last_login IS NULL;')
