# Generated by Django 4.1.1 on 2023-05-01 08:30

from django.db import migrations

def set_default_password(apps, schema_editor):
    User = apps.get_model('main_app', 'User')
    User.objects.filter(password=None).update(password='')

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003'),
    ]

    operations = [
        migrations.RunPython(set_default_password),
    ]